name: Deploy Frontend CD

on:
  push:
    branches:
      - desenvolvimento

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull latest Docker image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKERHUB_USER }}/codetech-front:v14

      - name: Stop existing container (if running)
        run: sudo docker stop $(docker ps -q --filter label=app=container-front) || true

      - name: Remove existing container (if exists)
        run: sudo docker rm $(docker ps -aq --filter label=app=container-front) || true

      - name: Run Docker container with the new image
        run: sudo docker run --name container-front -d -p 3000:80 --label app=container-front ${{ secrets.DOCKERHUB_USER }}/codetech-front:latest
