name: CI Frontend React

on:
  push:
    branches: [ desenvolvimento ]
  pull_request:
    branches: [ desenvolvimento ]

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # ou a versão do Node.js que seu projeto utiliza

      - name: Install dependencies
        run: npm install
        working-directory: ./code-front

      - name: Build React app
        run: npm run build
        working-directory: ./code-front
        env:
          CI: false

      # Opcional: Adicionar um passo para verificar se a build foi bem-sucedida
      - name: Check build output
        run: |
          if [ -d "./code-front/build" ]; then
            echo "Build realizado com sucesso!"
          else
            echo "Erro: Diretório de build não encontrado."
            exit 1
          fi
        working-directory: ./code-front

      # Opcional: Adicionar passos para testes (se você tiver configurado)
      # - name: Run tests
      #   run: npm run test
      #   working-directory: ./code-front

      # Opcional: Adicionar passos para deploy (dependendo do seu ambiente)
      # - name: Deploy to production
      #   if: github.ref == 'refs/heads/desenvolvimento'
      #   run: |
      #     # Comandos de deploy aqui
      #     echo "Deploying to production..."
      #   working-directory: ./code-front