name: CI Frontend React

on:
  pull_request:
    branches:
      - desenvolvimento # A branch para a qual a PR está sendo aberta
    types: [ opened, reopened ] # Dispara quando a PR é aberta ou reaberta

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./code-front

      - name: Run tests
        run: npm run test -- --watchAll=false
        working-directory: ./code-front

      - name: Build React app
        run: npm run build
        working-directory: ./code-front
        env:
          CI: false

      - name: Check build output
        run: |
          cd ./code-front
          if [ -d "./build" ]; then
            echo "Build realizado com sucesso!"
          else
            echo "Erro: Diretório de build não encontrado."
            exit 1
          fi

      # Opcional: Adicionar passos para testes (se você tiver configurado)
      # - name: Run tests
      #   run: npm run test
      #   working-directory: ./code-front

      # Opcional: Adicionar passos para deploy (dependendo do seu ambiente)
      # - name: Deploy to production
      #   if: github.ref == 'refs/heads/desenvolvimento'
      #   run: |
      #     # Comandos de deploy aqui
      #     echo "Deploying to production..."
      #   working-directory: ./code-front