name: CI Frontend CodeTech

on:
  push:
    branches: [ desenvolvimento ]
  #pull_request:
    #branches: [ main ]

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # ou a versão do Node.js que seu projeto utiliza

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      # Opcional: Adicionar um passo para verificar se a build foi bem-sucedida
      - name: Check build output
        run: |
          if [ -d "./build" ]; then
            echo "Build realizado com sucesso!"
          else
            echo "Erro: Diretório de build não encontrado."
            exit 1
          fi

      # Opcional: Adicionar passos para testes (se você tiver configurado)
      # - name: Run tests
      #   run: npm run test

      # Opcional: Adicionar passos para deploy (dependendo do seu ambiente)
      # - name: Deploy to production
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     # Comandos de deploy aqui
      #     echo "Deploying to production..."